/* Generated by build_static.py — do not edit; rebuild instead. */
const CACHE = "quiz-595aa759b9c6";
const ASSETS = ["./", "./index.html", "./manifest.webmanifest",
                "./icon-192.png", "./icon-512.png"];

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // One bad URL must not abandon the whole precache.
    await Promise.all(ASSETS.map(async url => {
      try { await cache.add(new Request(url, { cache: "reload" })); }
      catch (err) { console.warn("precache skipped", url, err); }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET") return;

  // Any navigation lands on the app shell, cached or not.
  if (req.mode === "navigate") {
    event.respondWith((async () => {
      const hit = await caches.match("./index.html");
      if (hit) return hit;
      try { return await fetch(req); }
      catch (err) { return new Response("offline", { status: 503 }); }
    })());
    return;
  }

  event.respondWith((async () => {
    const hit = await caches.match(req);
    if (hit) return hit;
    try {
      const res = await fetch(req);
      if (res.ok && new URL(req.url).origin === self.location.origin) {
        const cache = await caches.open(CACHE);
        cache.put(req, res.clone());
      }
      return res;
    } catch (err) {
      return new Response("offline", { status: 503 });
    }
  })());
});
